Trace1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('secretary/', include('secretary.urls')),
    path('director/', include('director.urls')),
    path('manager/', include('manager.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

manager/urls.py
from django.urls import path

from . import views

app_name = 'manager'
urlpatterns = [
    path('projects/', views.projects_view, name='projects'),
    path('projects/<pk>/phases', views.phases_view, name='phases'),
    path('projects/<pk>/phases/new', views.new_phase_view, name='new_phase'),
    path('projects/<pk>/phases/<phase_pk>/edit', views.edit_phase_view, name='edit_phase'),
    path('projects/<pk>/phases/<phase_pk>/delete', views.delete_phase_view, name='delete_phase'),
]

manager/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models

from accounts.models import User


class Organisation(models.Model):
    code = models.CharField(max_length=20, unique=True, primary_key=True)
    nom = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    telephone = models.CharField(max_length=200)
    contact_name = models.CharField(max_length=200)
    contact_email = models.CharField(max_length=200)
    website = models.CharField(max_length=200)


# Create your models here.
class Project(models.Model):
    code = models.CharField(max_length=20, unique=True, primary_key=True)
    nom = models.CharField(max_length=200)
    description = models.TextField()
    client = models.ForeignKey(
        Organisation,
        on_delete=models.CASCADE,
        related_name="projects",
    )
    start_date = models.DateField()
    end_date = models.DateField()
    budget = models.IntegerField()
    chief = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="directed_projects",
        null=True,
    )


class Phase(models.Model):
    code = models.CharField(max_length=20, unique=True, primary_key=True)
    nom = models.CharField(max_length=200)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name="phases",
    )
    start_date = models.DateField()
    end_date = models.DateField()
    team = models.ManyToManyField(
        User,
        related_name="phases",
    )
    percentage = models.IntegerField()
    finished = models.BooleanField()
    invoiced = models.BooleanField()
    payed = models.BooleanField()
    

class Deliverable(models.Model):
    code = models.CharField(max_length=20, unique=True, primary_key=True)
    nom = models.CharField(max_length=200)
    description = models.TextField()
    phase = models.ForeignKey(
        Phase,
        on_delete=models.CASCADE,
        related_name="deliverables",
    )
    file = models.FileField(upload_to="deliverables")

manager/views.py
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import render
from accounts.models import User


# Create your views here.
def projects_view(request):
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_chief():
            return render(request, 'manager/projects.html', {
                'projects': user.directed_projects.all(),
            })
    raise PermissionError


def phases_view(request, pk):
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_chief():
            project = user.directed_projects.get(pk=pk)
            return render(request, 'manager/phases.html', {
                'phases': project.phases.all(),
                'project': project,
            })
    raise PermissionError


def save_team(phase, request):
    phase.team.clear()
    for t in request.POST.getlist('team'):
        u = User.objects.get(username=t)
        phase.team.add(u)


def save_phase(phase, request):
    phase.nom = request.POST.get('nom')
    phase.description = request.POST.get('description')
    phase.start_date = request.POST.get('start_date')
    phase.end_date = request.POST.get('end_date')
    phase.percentage = request.POST.get('percentage')
    phase.finished = request.POST.get('finished', 'off') == 'on'
    save_team(phase, request)
    phase.save()


def new_phase_view(request, pk):
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_chief():
            project = user.directed_projects.get(pk=pk)
            if request.method == 'GET':
                return render(request, 'manager/new_phase.html', {
                    'members': User.objects.all(),
                    'project': project,
                })
            phase = project.phases.create(
                code=request.POST.get('code'),
                nom=request.POST.get('nom'),
                description=request.POST.get('description'),
                start_date=request.POST.get('start_date'),
                end_date=request.POST.get('end_date'),
                percentage=request.POST.get('percentage'),
                invoiced=False,
                finished=request.POST.get('finished', 'off') == 'on',
                payed=False,
            )
            save_team(phase, request)
            phase.save()
            return render(request, 'manager/phase_row.html', {
                    'phase': phase,
                    'project': project,
            })
    raise PermissionError


def edit_phase_view(request, pk, phase_pk):
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_chief():
            phase = user.directed_projects.get(pk=pk).phases.get(pk=phase_pk)
            if request.method == 'GET':
                return render(request, 'manager/edit_phase.html', {
                    'phase': phase,
                    'project': phase.project,
                    'team': [x.username for x in phase.team.all()],
                    'members': User.objects.all(),
                })
            save_phase(phase, request)
            return render(request, 'manager/phase_row.html', {
                    'phase': phase,
                    'project': phase.project,
            })
    raise PermissionError


def delete_phase_view(request, pk, phase_pk):
    if request.method != 'DELETE':
        return HttpResponse(status=405)
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_superuser or user.is_chief():
            phase = user.directed_projects.get(pk=pk).phases.get(pk=phase_pk)
            phase.delete()
            return HttpResponse(status=200, content="")
    raise PermissionDenied

projects/views.py
from django.shortcuts import render

# Create your views here.

manager/templates/manager/edit_phase.html
<div id="modal">
    <h2 class="text-xl text-content1">Edit Phase</h2>
    <br>
    <form class="form-group" hx-post="{% url 'manager:edit_phase' project.code phase.code %}"
          hx-target="#phase-{{ phase.code }}" hx-swap="outerHTML"
          _="on htmx:afterRequest set #modal-edit.checked to false wait 200ms then remove #modal">
        {% csrf_token %}
        <div class="form-field">
            <label for="code" class="form-label">Code:</label>
            <input id="code" name="code" class="input-block input" value="{{ phase.code }}" disabled/>
        </div>
        <div class="form-field">
            <label for="nom" class="form-label">Name:</label>
            <input id="nom" name="nom" class="input-block input" value="{{ phase.nom }}"/>
        </div>
        <div class="form-field">
            <label for="description" class="form-label">Description:</label>
            <input id="description" name="description" class="input-block input" value="{{ phase.description }}"/>
        </div>
        <div class="form-field">
            <label for="start_date" class="form-label">Start Date:</label>
            <input type="date" name="start_date" id="start_date" class="input-block input"
                   value="{{ phase.start_date | date:"Y-m-d" }}"/>
        </div>
        <div class="form-field">
            <label for="end_date" class="form-label">End Date:</label>
            <input type="date" name="end_date" id="end_date" class="input-block input"
                   value="{{ phase.end_date | date:"Y-m-d" }}"/>
        </div>
        <div class="form-field">
            <label for="percentage" class="form-label">Percentage:</label>
            <input type="number" name="percentage" id="percentage" class="input-block input" value="{{ phase.percentage }}"/>
        </div>
        <div class="form-field">
            <label for="team">Team:</label>
            <select name="team" id="team" class="input input-block h-auto" multiple>
                {% for member in members %}
                    <option value="{{ member.username }}"{% if member.username in team %}
                            selected{% endif %}>{{ member.username }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-field">
            <label for="finished" class="form-label">Finished:</label>
            <input type="checkbox" name="finished" id="finished" class="checkbox"
                   {% if phase.finished %}checked{% endif %}/>
        </div>
        {% include 'core/modal_buttons.html' %}
    </form>
</div>

manager/templates/manager/new_phase.html
<div id="modal">
    <h2 class="text-xl text-content1">New Phase</h2>
    <br>
    <form class="form-group"
          hx-post="{% url 'manager:new_phase' project.code %}" hx-target="#table-body" hx-swap="beforeend"
          _="on htmx:afterRequest set #modal-edit.checked to false wait 200ms then remove #modal">
        {% csrf_token %}
        <div class="form-field">
            <label for="code" class="form-label">Code:</label>
            <input id="code" name="code" class="input-block input"/>
        </div>
        <div class="form-field">
            <label for="nom" class="form-label">Name:</label>
            <input id="nom" name="nom" class="input-block input"/>
        </div>
        <div class="form-field">
            <label for="description" class="form-label">Description:</label>
            <input id="description" name="description" class="input-block input"/>
        </div>
        <div class="form-field">
            <label for="start_date" class="form-label">Start Date:</label>
            <input type="date" name="start_date" id="start_date" class="input-block input"/>
        </div>
        <div class="form-field">
            <label for="end_date" class="form-label">End Date:</label>
            <input type="date" name="end_date" id="end_date" class="input-block input"/>
        </div>
        <div class="form-field">
            <label for="percentage" class="form-label">Percentage:</label>
            <input type="number" name="percentage" id="percentage" class="input-block input"/>
        </div>
        <div class="form-field">
            <label for="team">Team:</label>
            <select name="team" id="team" class="input input-block h-auto" multiple>
                {% for member in members %}
                    <option value="{{ member.username }}">{{ member.username }}</option>
                {% endfor %}
            </select>
        </div>
        {% include 'core/modal_buttons.html' %}
    </form>
</div>

manager/templates/manager/phase_row.html
<tr id="phase-{{ phase.code }}">
    <td>{{ phase.code }}</td>
    <td>{{ phase.nom }}</td>
    <td>{{ phase.description | truncatewords:10 }}</td>
    <td>
        <button
                hx-get="{% url 'manager:edit_phase' project.code phase.code %}"
                hx-target="#modals-here"
                class="btn btn-ghost"
                _="on htmx:afterOnLoad wait 10ms then set #modal-edit.checked to true">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                 stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M20 14.66V20a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h5.34"></path>
                <polygon points="18 2 22 6 12 16 8 16 8 12 18 2"></polygon>
            </svg>
        </button>
        <button class="link text-red-500"
                hx-target="#phase-{{ phase.code }}"
                hx-swap="outerHTML swap:1s"
                hx-delete="{% url 'manager:delete_phase' project.code phase.code %}"
                hx-confirm="Do you want to delete {{ phase.code }} ?">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                 stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <polyline points="3 6 5 6 21 6"></polyline>
                <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
                <line x1="10" y1="11" x2="10" y2="17"></line>
                <line x1="14" y1="11" x2="14" y2="17"></line>
            </svg>
        </button>
    </td>
</tr>

manager/templates/manager/phases.html
{% extends 'core/base.html' %}

{% block title %}Projects{% endblock %}

{% block content %}
    <div class="max-w-screen-md mx-auto my-0.5 p-4">
        <table class="table-compact table overflow-x-scroll">
            <thead>
            <tr>
                <th>Code</th>
                <th>Nom</th>
                <th>Description</th>
                <th class="w-20 min-w-[80px]">
                    <button
                            hx-get="{% url 'manager:new_phase' project.code %}"
                            hx-target="#modals-here"
                            class="btn btn-ghost border-transparent"
                            _="on htmx:afterOnLoad wait 10ms then set #modal-edit.checked to true">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                             stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                            <line x1="12" y1="5" x2="12" y2="19"></line>
                            <line x1="5" y1="12" x2="19" y2="12"></line>
                        </svg>
                    </button>
                </th>
            </tr>
            </thead>
            <tbody id="table-body">
            {% for phase in phases %}
                {% include 'manager/phase_row.html' %}
            {% endfor %}

            </tbody>
        </table>
    </div>
{% endblock %}

manager/templates/manager/project_row.html
<tr id="project-{{ project.code }}">
    <td>{{ project.code }}</td>
    <td>{{ project.nom }}</td>
    <td>{{ project.description | truncatewords:10 }}</td>
    <td><a href="{% url 'manager:phases' project.code %}" class="btn btn-primary">Phases</a></td>
</tr>

manager/templates/manager/projects.html
{% extends 'core/base.html' %}

{% block title %}Projects{% endblock %}

{% block content %}
    <div class="max-w-screen-md mx-auto my-0.5 p-4">
        <table class="table-compact table overflow-x-scroll">
            <thead>
            <tr>
                <th>Code</th>
                <th>Nom</th>
                <th>Description</th>
                <th class="w-20 min-w-[80px]"></th>
            </tr>
            </thead>
            <tbody id="table-body">
            {% for project in projects %}
                {% include 'manager/project_row.html' %}
            {% endfor %}

            </tbody>
        </table>
    </div>
{% endblock %}