Trace1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('secretary/', include('secretary.urls')),
    path('director/', include('director.urls')),
    path('manager/', include('manager.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

director/urls.py
from django.urls import path

from .views import projects_view, edit_project_view, new_project_view, delete_project_view

app_name = "director"
urlpatterns = [
    path("projects/", view=projects_view, name="projects"),
    path("projects/new/", view=new_project_view, name="new_project"),
    path("projects/edit/<pk>/", view=edit_project_view, name="edit_project"),
    path("projects/delete/<pk>", view=delete_project_view, name="delete_project"),
]

manager/urls.py
from django.urls import path

from . import views

app_name = 'manager'
urlpatterns = [
    path('projects/', views.projects_view, name='projects'),
    path('projects/<pk>/phases', views.phases_view, name='phases'),
    path('projects/<pk>/phases/new', views.new_phase_view, name='new_phase'),
    path('projects/<pk>/phases/<phase_pk>/edit', views.edit_phase_view, name='edit_phase'),
    path('projects/<pk>/phases/<phase_pk>/delete', views.delete_phase_view, name='delete_phase'),
]

secretary/urls.py
from django.urls import path

from .views import projects_view, edit_project_view, new_project_view, clients_view, edit_client_view, new_client_view, \
    delete_project_view, delete_client_view

app_name = "secretary"
urlpatterns = [
    path("projects/", view=projects_view, name="projects"),
    path("projects/new/", view=new_project_view, name="new_project"),
    path("projects/edit/<pk>/", view=edit_project_view, name="edit_project"),
    path("projects/delete/<pk>", view=delete_project_view, name="delete_project"),
    path("clients/", view=clients_view, name="clients"),
    path("clients/new/", view=new_client_view, name="new_client"),
    path("clients/edit/<pk>/", view=edit_client_view, name="edit_client"),
    path("clients/delete/<pk>", view=delete_client_view, name="delete_client")
]

core/models.py
from django.db import models

# Create your models here.

director/models.py
from django.db import models

# Create your models here.

manager/models.py
from django.db import models

# Create your models here.

secretary/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'core/index.html')

director/views.py
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import render
from accounts.models import User
from projects.models import Project, Organisation


def projects_view(request):
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_superuser or user.is_director():
            return render(request, 'director/projects.html', {
                'projects': Project.objects.all(),
            })
    raise PermissionDenied


def save_project(project, request):
    project.nom = request.POST['nom']
    project.budget = request.POST['budget']
    project.chief = User.objects.get(username=request.POST['chief'])
    project.description = request.POST['description']
    project.client = Organisation.objects.get(code=request.POST['client'])
    project.start_date = request.POST['start_date']
    project.end_date = request.POST['end_date']
    project.save()


def new_project_view(request):
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_superuser or user.is_director():
            if request.method == 'GET':
                return render(request, 'director/new_project.html', {
                    'organisations': Organisation.objects.all(),
                    'chiefs': [x for x in User.objects.all() if x.is_chief()],
                })
            project = Project()
            project.code = request.POST['code']
            save_project(project, request)
            return render(request, 'director/project_row.html', {
                'project': project,
            })
    raise PermissionDenied


def edit_project_view(request, pk):
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_superuser or user.is_director():
            if request.method == 'GET':
                return render(request, 'director/edit_project.html', {
                    'project': Project.objects.get(pk=pk),
                    'organisations': Organisation.objects.all(),
                    'chiefs': [x for x in User.objects.all() if x.is_chief()],
                })
            project = Project.objects.get(pk=pk)
            save_project(project, request)
            return render(request, 'director/project_row.html', {
                'project': project,
            })
    raise PermissionDenied


def delete_project_view(request, pk):
    if request.method != 'DELETE':
        return HttpResponse(status=405)
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_superuser or user.is_director():
            project = Project.objects.get(pk=pk)
            project.delete()
            return HttpResponse(status=200, content="")
    raise PermissionDenied

manager/views.py
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import render
from accounts.models import User


# Create your views here.
def projects_view(request):
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_chief():
            return render(request, 'manager/projects.html', {
                'projects': user.directed_projects.all(),
            })
    raise PermissionError


def phases_view(request, pk):
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_chief():
            project = user.directed_projects.get(pk=pk)
            return render(request, 'manager/phases.html', {
                'phases': project.phases.all(),
                'project': project,
            })
    raise PermissionError


def save_team(phase, request):
    phase.team.clear()
    for t in request.POST.getlist('team'):
        u = User.objects.get(username=t)
        phase.team.add(u)


def save_phase(phase, request):
    phase.nom = request.POST.get('nom')
    phase.description = request.POST.get('description')
    phase.start_date = request.POST.get('start_date')
    phase.end_date = request.POST.get('end_date')
    phase.percentage = request.POST.get('percentage')
    phase.finished = request.POST.get('finished', 'off') == 'on'
    save_team(phase, request)
    phase.save()


def new_phase_view(request, pk):
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_chief():
            project = user.directed_projects.get(pk=pk)
            if request.method == 'GET':
                return render(request, 'manager/new_phase.html', {
                    'members': User.objects.all(),
                    'project': project,
                })
            phase = project.phases.create(
                code=request.POST.get('code'),
                nom=request.POST.get('nom'),
                description=request.POST.get('description'),
                start_date=request.POST.get('start_date'),
                end_date=request.POST.get('end_date'),
                percentage=request.POST.get('percentage'),
                invoiced=False,
                finished=request.POST.get('finished', 'off') == 'on',
                payed=False,
            )
            save_team(phase, request)
            phase.save()
            return render(request, 'manager/phase_row.html', {
                    'phase': phase,
                    'project': project,
            })
    raise PermissionError


def edit_phase_view(request, pk, phase_pk):
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_chief():
            phase = user.directed_projects.get(pk=pk).phases.get(pk=phase_pk)
            if request.method == 'GET':
                return render(request, 'manager/edit_phase.html', {
                    'phase': phase,
                    'project': phase.project,
                    'team': [x.username for x in phase.team.all()],
                    'members': User.objects.all(),
                })
            save_phase(phase, request)
            return render(request, 'manager/phase_row.html', {
                    'phase': phase,
                    'project': phase.project,
            })
    raise PermissionError


def delete_phase_view(request, pk, phase_pk):
    if request.method != 'DELETE':
        return HttpResponse(status=405)
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_superuser or user.is_chief():
            phase = user.directed_projects.get(pk=pk).phases.get(pk=phase_pk)
            phase.delete()
            return HttpResponse(status=200, content="")
    raise PermissionDenied

secretary/views.py
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import render
from accounts.models import User
from projects.models import Project, Organisation


def projects_view(request):
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_superuser or user.is_secretary():
            return render(request, 'secretary/projects.html', {
                'projects': Project.objects.all(),
            })
    raise PermissionDenied


def save_project(project, request):
    project.nom = request.POST['nom']
    project.description = request.POST['description']
    project.client = Organisation.objects.get(code=request.POST['client'])
    project.start_date = request.POST['start_date']
    project.end_date = request.POST['end_date']
    project.save()


def new_project_view(request):
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_superuser or user.is_secretary():
            if request.method == 'GET':
                return render(request, 'secretary/new_project.html', {
                    'organisations': Organisation.objects.all(),
                })
            project = Project()
            project.code = request.POST['code']
            project.budget = 0
            save_project(project, request)
            return render(request, 'secretary/project_row.html', {
                'project': project,
            })
    raise PermissionDenied


def edit_project_view(request, pk):
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_superuser or user.is_secretary():
            if request.method == 'GET':
                return render(request, 'secretary/edit_project.html', {
                    'project': Project.objects.get(pk=pk),
                    'organisations': Organisation.objects.all(),
                })
            project = Project.objects.get(pk=pk)
            save_project(project, request)
            return render(request, 'secretary/project_row.html', {
                'project': project,
            })
    raise PermissionDenied


def clients_view(request):
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_superuser or user.is_secretary():
            return render(request, 'secretary/clients.html', {
                'organisations': Organisation.objects.all(),
            })
    raise PermissionDenied


def save_client(organisation, request):
    organisation.nom = request.POST['nom']
    organisation.address = request.POST['address']
    organisation.telephone = request.POST['telephone']
    organisation.contact_name = request.POST['contact_name']
    organisation.contact_email = request.POST['contact_email']
    organisation.website = request.POST['website']
    organisation.save()


def new_client_view(request):
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_superuser or user.is_secretary():
            if request.method == 'GET':
                return render(request, 'secretary/new_client.html', {})
            organisation = Organisation()
            organisation.code = request.POST['code']
            save_client(organisation, request)
            return render(request, 'secretary/client_row.html', {
                'client': organisation,
            })
    raise PermissionDenied


def edit_client_view(request, pk):
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_superuser or user.is_secretary():
            if request.method == 'GET':
                return render(request, 'secretary/edit_client.html', {
                    'client': Organisation.objects.get(pk=pk),
                })
            organisation = Organisation.objects.get(pk=pk)
            save_client(organisation, request)
            return render(request, 'secretary/client_row.html', {
                'client': organisation,
            })
    raise PermissionDenied


def delete_project_view(request, pk):
    if request.method != 'DELETE':
        return HttpResponse(status=405)
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_superuser or user.is_secretary():
            project = Project.objects.get(pk=pk)
            project.delete()
            return HttpResponse(status=200, content="")
    raise PermissionDenied


def delete_client_view(request, pk):
    if request.method != 'DELETE':
        return HttpResponse(status=405)
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_superuser or user.is_secretary():
            client = Organisation.objects.get(pk=pk)
            client.delete()
            return HttpResponse(status=200, content="")
    raise PermissionDenied

core/templates/core/sidebars/director.html
<section class="menu-section px-4">
    <span class="menu-title">Director</span>
    <ul class="menu-items">
        {% url 'director:projects' as director_projects %}
        {% include 'core/sidebars/line.html' with name='Projects' url=director_projects icon='gears' active='/director/projects/' %}
    </ul>
</section>

core/templates/core/sidebars/line.html
<a class="link w-full hover:no-underline" href="{{ url }}">
    <li class="menu-item w-full{% if request.path == active %} menu-active{% endif %}">
        {% if icon == 'gears' %}
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 opacity-75" fill="none" viewBox="0 0 24 24"
                 stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round"
                      d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"></path>
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
            </svg>
        {% elif icon == 'compass' %}
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 opacity-75" viewBox="0 0 24 24" fill="none"
                 stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <circle cx="12" cy="12" r="10"></circle>
                <path d="M16.2 7.8l-2 6.3-6.4 2.1 2-6.3z"></path>
            </svg>
        {% elif icon == 'users' %}
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 opacity-75" fill="none" viewBox="0 0 24 24"
                 stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round"
                      d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"></path>
            </svg>
        {% endif %}
        <span>{{ name }}</span>
    </li>
</a>

core/templates/core/sidebars/logged_out.html
<section class="menu-section px-4">
    <span class="menu-title">Main menu</span>
    <ul class="menu-items">
        <li class="menu-item">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 opacity-75" fill="none" viewBox="0 0 24 24"
                 stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round"
                      d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"></path>
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
            </svg>
            <span>General</span>
        </li>

        <li class="menu-item menu-active">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 opacity-75" fill="none" viewBox="0 0 24 24"
                 stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round"
                      d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z"></path>
            </svg>
            <span>Teams</span>
        </li>
        <li class="menu-item">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 opacity-75" fill="none" viewBox="0 0 24 24"
                 stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round"
                      d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z"></path>
            </svg>
            <span>Billing</span>
        </li>
        <li>
            <input type="checkbox" id="menu-1" class="menu-toggle"/>
            <label class="menu-item justify-between" for="menu-1">
                <div class="flex gap-2">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 opacity-75" fill="none" viewBox="0 0 24 24"
                         stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round"
                              d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path>
                    </svg>
                    <span>Account</span>
                </div>

                <span class="menu-icon">
										<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20"
                                             fill="currentColor">
											<path fill-rule="evenodd"
                                                  d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                                                  clip-rule="evenodd"></path>
										</svg>
									</span>
            </label>

            <div class="menu-item-collapse">
                <div class="min-h-0">
                    <label class="menu-item menu-item-disabled ml-6">Change Email</label>
                    <label class="menu-item ml-6">Profile</label>
                    <label class="menu-item ml-6">Change Password</label>
                </div>
            </div>
        </li>
    </ul>
</section>
<div class="divider my-0"></div>
<section class="menu-section px-4">
    <span class="menu-title">Settings</span>
    <ul class="menu-items">
        <li class="menu-item">
            <svg xmlns="http://www.w3.org/2000/svg" class="opacity-75" width="22" height="22" viewBox="0 0 24 24"
                 stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                <path d="M3 21l18 0"></path>
                <path d="M3 10l18 0"></path>
                <path d="M5 6l7 -3l7 3"></path>
                <path d="M4 10l0 11"></path>
                <path d="M20 10l0 11"></path>
                <path d="M8 14l0 3"></path>
                <path d="M12 14l0 3"></path>
                <path d="M16 14l0 3"></path>
            </svg>
            Payments
        </li>
        <li class="menu-item">
            <svg xmlns="http://www.w3.org/2000/svg" class="opacity-75" width="22" height="22" viewBox="0 0 24 24"
                 stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                <path d="M7 9m0 2a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v6a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2z"></path>
                <path d="M14 14m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"></path>
                <path d="M17 9v-2a2 2 0 0 0 -2 -2h-10a2 2 0 0 0 -2 2v6a2 2 0 0 0 2 2h2"></path>
            </svg>
            Balances
        </li>
        <li class="menu-item">
            <svg xmlns="http://www.w3.org/2000/svg" class="opacity-75" width="22" height="22" viewBox="0 0 24 24"
                 stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                <path d="M9 7m-4 0a4 4 0 1 0 8 0a4 4 0 1 0 -8 0"></path>
                <path d="M3 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2"></path>
                <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                <path d="M21 21v-2a4 4 0 0 0 -3 -3.85"></path>
            </svg>
            Customers
        </li>
        <li class="menu-item">
            <svg xmlns="http://www.w3.org/2000/svg" class="opacity-75" width="22" height="22" viewBox="0 0 24 24"
                 stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                <path d="M7 10l5 -6l5 6"></path>
                <path d="M21 10l-2 8a2 2.5 0 0 1 -2 2h-10a2 2.5 0 0 1 -2 -2l-2 -8z"></path>
                <path d="M12 15m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"></path>
            </svg>
            Products
        </li>
        <li>
            <input type="checkbox" id="menu-2" class="menu-toggle"/>
            <label class="menu-item justify-between" for="menu-2">
                <div class="flex gap-2">
                    <svg xmlns="http://www.w3.org/2000/svg" class="opacity-75" width="22" height="22"
                         viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round"
                         stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                        <path d="M15 21h-9a3 3 0 0 1 -3 -3v-1h10v2a2 2 0 0 0 4 0v-14a2 2 0 1 1 2 2h-2m2 -4h-11a3 3 0 0 0 -3 3v11"></path>
                        <path d="M9 7l4 0"></path>
                        <path d="M9 11l4 0"></path>
                    </svg>
                    <span>Contracts</span>
                </div>

                <span class="menu-icon">
										<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20"
                                             fill="currentColor">
											<path fill-rule="evenodd"
                                                  d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                                                  clip-rule="evenodd"></path>
										</svg>
									</span>
            </label>

            <div class="menu-item-collapse">
                <div class="min-h-0">
                    <label class="menu-item menu-item-disabled ml-6">Create contract</label>
                    <label class="menu-item ml-6">All contracts</label>
                    <label class="menu-item ml-6">Pending contracts</label>
                    <label class="menu-item ml-6">Security</label>
                </div>
            </div>
        </li>
    </ul>
</section>
</nav>
</section>

core/templates/core/sidebars/manager.html
<section class="menu-section px-4">
    <span class="menu-title">Chief</span>
    <ul class="menu-items">
        {% url 'manager:projects' as manager_projects %}
        {% include 'core/sidebars/line.html' with name='Projects' url=manager_projects icon='gears' active='/manager/projects/' %}
    </ul>
</section>

core/templates/core/sidebars/secretary.html
<section class="menu-section px-4">
    <span class="menu-title">Secretary</span>
    <ul class="menu-items">
        {% url 'secretary:projects' as secretary_projects %}
        {% url 'secretary:clients' as secretary_clients %}
        {% include 'core/sidebars/line.html' with name='Projects' url=secretary_projects icon='gears' active='/secretary/projects/' %}
        {% include 'core/sidebars/line.html' with name='Clients' url=secretary_clients icon='compass' active='/secretary/clients/' %}
    </ul>
</section>

core/templates/core/sidebars/superuser.html
<section class="menu-section px-4">
    <span class="menu-title">Super User</span>
    <ul class="menu-items">
        {% url 'admin:index' as admin_index %}
        {% include 'core/sidebars/line.html' with name='Admin' url=admin_index icon='gears' %}
    </ul>
</section>