Trace1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('secretary/', include('secretary.urls')),
    path('director/', include('director.urls')),
    path('manager/', include('manager.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

secretary/urls.py
from django.urls import path

from .views import projects_view, edit_project_view, new_project_view, clients_view, edit_client_view, new_client_view, \
    delete_project_view, delete_client_view

app_name = "secretary"
urlpatterns = [
    path("projects/", view=projects_view, name="projects"),
    path("projects/new/", view=new_project_view, name="new_project"),
    path("projects/edit/<pk>/", view=edit_project_view, name="edit_project"),
    path("projects/delete/<pk>", view=delete_project_view, name="delete_project"),
    path("clients/", view=clients_view, name="clients"),
    path("clients/new/", view=new_client_view, name="new_client"),
    path("clients/edit/<pk>/", view=edit_client_view, name="edit_client"),
    path("clients/delete/<pk>", view=delete_client_view, name="delete_client")
]

projects/models.py
from django.db import models

from accounts.models import User


class Organisation(models.Model):
    code = models.CharField(max_length=20, unique=True, primary_key=True)
    nom = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    telephone = models.CharField(max_length=200)
    contact_name = models.CharField(max_length=200)
    contact_email = models.CharField(max_length=200)
    website = models.CharField(max_length=200)


# Create your models here.
class Project(models.Model):
    code = models.CharField(max_length=20, unique=True, primary_key=True)
    nom = models.CharField(max_length=200)
    description = models.TextField()
    client = models.ForeignKey(
        Organisation,
        on_delete=models.CASCADE,
        related_name="projects",
    )
    start_date = models.DateField()
    end_date = models.DateField()
    budget = models.IntegerField()
    chief = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="directed_projects",
        null=True,
    )


class Phase(models.Model):
    code = models.CharField(max_length=20, unique=True, primary_key=True)
    nom = models.CharField(max_length=200)
    description = models.TextField()
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name="phases",
    )
    start_date = models.DateField()
    end_date = models.DateField()
    team = models.ManyToManyField(
        User,
        related_name="phases",
    )
    percentage = models.IntegerField()
    finished = models.BooleanField()
    invoiced = models.BooleanField()
    payed = models.BooleanField()
    

class Deliverable(models.Model):
    code = models.CharField(max_length=20, unique=True, primary_key=True)
    nom = models.CharField(max_length=200)
    description = models.TextField()
    phase = models.ForeignKey(
        Phase,
        on_delete=models.CASCADE,
        related_name="deliverables",
    )
    file = models.FileField(upload_to="deliverables")

secretary/models.py
from django.db import models

# Create your models here.

projects/views.py
from django.shortcuts import render

# Create your views here.

secretary/views.py
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import render
from accounts.models import User
from projects.models import Project, Organisation


def projects_view(request):
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_superuser or user.is_secretary():
            return render(request, 'secretary/projects.html', {
                'projects': Project.objects.all(),
            })
    raise PermissionDenied


def save_project(project, request):
    project.nom = request.POST['nom']
    project.description = request.POST['description']
    project.client = Organisation.objects.get(code=request.POST['client'])
    project.start_date = request.POST['start_date']
    project.end_date = request.POST['end_date']
    project.save()


def new_project_view(request):
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_superuser or user.is_secretary():
            if request.method == 'GET':
                return render(request, 'secretary/new_project.html', {
                    'organisations': Organisation.objects.all(),
                })
            project = Project()
            project.code = request.POST['code']
            project.budget = 0
            save_project(project, request)
            return render(request, 'secretary/project_row.html', {
                'project': project,
            })
    raise PermissionDenied


def edit_project_view(request, pk):
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_superuser or user.is_secretary():
            if request.method == 'GET':
                return render(request, 'secretary/edit_project.html', {
                    'project': Project.objects.get(pk=pk),
                    'organisations': Organisation.objects.all(),
                })
            project = Project.objects.get(pk=pk)
            save_project(project, request)
            return render(request, 'secretary/project_row.html', {
                'project': project,
            })
    raise PermissionDenied


def clients_view(request):
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_superuser or user.is_secretary():
            return render(request, 'secretary/clients.html', {
                'organisations': Organisation.objects.all(),
            })
    raise PermissionDenied


def save_client(organisation, request):
    organisation.nom = request.POST['nom']
    organisation.address = request.POST['address']
    organisation.telephone = request.POST['telephone']
    organisation.contact_name = request.POST['contact_name']
    organisation.contact_email = request.POST['contact_email']
    organisation.website = request.POST['website']
    organisation.save()


def new_client_view(request):
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_superuser or user.is_secretary():
            if request.method == 'GET':
                return render(request, 'secretary/new_client.html', {})
            organisation = Organisation()
            organisation.code = request.POST['code']
            save_client(organisation, request)
            return render(request, 'secretary/client_row.html', {
                'client': organisation,
            })
    raise PermissionDenied


def edit_client_view(request, pk):
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_superuser or user.is_secretary():
            if request.method == 'GET':
                return render(request, 'secretary/edit_client.html', {
                    'client': Organisation.objects.get(pk=pk),
                })
            organisation = Organisation.objects.get(pk=pk)
            save_client(organisation, request)
            return render(request, 'secretary/client_row.html', {
                'client': organisation,
            })
    raise PermissionDenied


def delete_project_view(request, pk):
    if request.method != 'DELETE':
        return HttpResponse(status=405)
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_superuser or user.is_secretary():
            project = Project.objects.get(pk=pk)
            project.delete()
            return HttpResponse(status=200, content="")
    raise PermissionDenied


def delete_client_view(request, pk):
    if request.method != 'DELETE':
        return HttpResponse(status=405)
    if request.user.is_authenticated:
        user = request.user  # type: User
        if user.is_superuser or user.is_secretary():
            client = Organisation.objects.get(pk=pk)
            client.delete()
            return HttpResponse(status=200, content="")
    raise PermissionDenied

secretary/templates/secretary/client_row.html
<tr id="client-{{ client.code }}">
    <td>{{ client.code }}</td>
    <td>{{ client.nom }}</td>
    <td>
        <button
                hx-get="{% url 'secretary:edit_client' client.code %}"
                hx-target="#modals-here"
                class="btn btn-ghost"
                _="on htmx:afterOnLoad wait 10ms then set #modal-edit.checked to true">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                 stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M20 14.66V20a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h5.34"></path>
                <polygon points="18 2 22 6 12 16 8 16 8 12 18 2"></polygon>
            </svg>
        </button>
        <button class="link text-red-500"
                hx-target="closest tr"
                hx-swap="outerHTML swap:1s"
                hx-delete="{% url 'secretary:delete_client' client.code %}"
                hx-confirm="Do you want to delete {{ client.code }} ?">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                 stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <polyline points="3 6 5 6 21 6"></polyline>
                <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
                <line x1="10" y1="11" x2="10" y2="17"></line>
                <line x1="14" y1="11" x2="14" y2="17"></line>
            </svg>
        </button>
    </td>
</tr>

secretary/templates/secretary/clients.html
{% extends 'core/base.html' %}

{% block title %}Projects{% endblock %}

{% block content %}
    <div class="max-w-screen-md mx-auto my-0.5 p-4">
        <table class="table-compact table overflow-x-scroll">
        <caption></caption>
        <thead>
        <tr>
            <th>Code</th>
            <th>Nom</th>
            <th class="w-20 min-w-[80px]">
                <button
                        hx-get="{% url 'secretary:new_client' %}"
                        hx-target="#modals-here"
                        class="btn btn-ghost border-transparent"
                        _="on htmx:afterOnLoad wait 10ms then set #modal-edit.checked to true">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                        <line x1="12" y1="5" x2="12" y2="19"></line>
                        <line x1="5" y1="12" x2="19" y2="12"></line>
                    </svg>
                </button>
            </th>
        </tr>
        </thead>
        <tbody id="table-body">
        {% for client in organisations %}
        	{% include 'secretary/client_row.html' %}
        {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock %}

secretary/templates/secretary/edit_client.html
<div id="modal">
    <h2 class="text-xl text-content1">Edit Client</h2>
    <br>
    <form class="form-group"
          hx-post="{% url 'secretary:edit_client' client.code %}" hx-target="#client-{{ client.code }}"
          hx-swap="outerHTML"
          _="on htmx:afterRequest set #modal-edit.checked to false wait 200ms then remove #modal">
        {% csrf_token %}
        <div class="form-field">
            <label for="code" class="form-label">Code:</label>
            <input id="code" name="code" class="input-block input" value="{{ client.code }}"/>
        </div>
        <div class="form-field">
            <label for="nom" class="form-label">Name:</label>
            <input id="nom" name="nom" class="input-block input" value="{{ client.nom }}"/>
        </div>
        <div class="form-field">
            <label for="address" class="form-label">Address:</label>
            <input id="address" name="address" class="input-block input" value="{{ client.address }}"/>
        </div>
        <div class="form-field">
            <label for="telephone" class="form-label">Telephone:</label>
            <input id="telephone" name="telephone" class="input-block input" value="{{ client.telephone }}"/>
        </div>
        <div class="form-field">
            <label for="contact_name" class="form-label">Contact Name:</label>
            <input id="contact_name" name="contact_name" class="input-block input" value="{{ client.contact_name }}"/>
        </div>
        <div class="form-field">
            <label for="contact_email" class="form-label">Contact Email:</label>
            <input id="contact_email" name="contact_email" class="input-block input"
                   value="{{ client.contact_email }}"/>
        </div>
        <div class="form-field">
            <label for="website" class="form-label">Website:</label>
            <input id="website" name="website" class="input-block input" value="{{ client.website }}"/>
        </div>
        {% include 'core/modal_buttons.html' %}
    </form>
</div>

secretary/templates/secretary/edit_project.html
<div id="modal">
    <h2 class="text-xl text-content1">Edit Project</h2>
    <br>
    <form class="form-group"
          hx-post="{% url 'secretary:edit_project' project.code %}" hx-target="#project-{{ project.code }}"
          hx-swap="outerHTML" _="on htmx:afterRequest set #modal-edit.checked to false wait 200ms then remove #modal">
        {% csrf_token %}
        <div class="form-field">
            <label for="code" class="form-label">Code:</label>
            <input id="code" name="code" class="input-block input" value="{{ project.code }}" disabled/>
        </div>
        <div class="form-field">
            <label for="nom" class="form-label">Name:</label>
            <input id="nom" name="nom" class="input-block input" value="{{ project.nom }}"/>
        </div>
        <div class="form-field">
            <label for="description" class="form-label">Description:</label>
            <input id="description" name="description" class="input-block input" value="{{ project.description }}"/>
        </div>
        <div class="form-field">
            <label for="client" class="form-label">Client:</label>
            <select name="client" id="client" class="select select-block">
                {% for organisation in organisations %}
                    <option value="{{ organisation.code }}"{% if organisation.code == project.client.code %}
                            selected{% endif %}>{{ organisation.code }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-field">
            <label for="start_date" class="form-label">Start Date:</label>
            <input type="date" name="start_date" id="start_date" class="input-block input"
                   value="{{ project.start_date | date:"Y-m-d" }}"/>
        </div>
        <div class="form-field">
            <label for="end_date" class="form-label">End Date:</label>
            <input type="date" name="end_date" id="end_date" class="input-block input"
                   value="{{ project.end_date | date:"Y-m-d" }}"/>
        </div>
        {% include 'core/modal_buttons.html' %}
    </form>
</div>

secretary/templates/secretary/new_client.html
<div id="modal">
    <h2 class="text-xl text-content1">New Client</h2>
    <br>
    <form class="form-group"
          hx-post="{% url 'secretary:new_client' %}" hx-target="#table-body" hx-swap="beforeend"
          _="on htmx:afterRequest set #modal-edit.checked to false wait 200ms then remove #modal">
        {% csrf_token %}
        <div class="form-field">
            <label for="code" class="form-label">Code:</label>
            <input id="code" name="code" class="input-block input" value="{{ client.code }}"/>
        </div>
        <div class="form-field">
            <label for="nom" class="form-label">Name:</label>
            <input id="nom" name="nom" class="input-block input" value="{{ client.nom }}"/>
        </div>
        <div class="form-field">
            <label for="address" class="form-label">Address:</label>
            <input id="address" name="address" class="input-block input" value="{{ client.address }}"/>
        </div>
        <div class="form-field">
            <label for="telephone" class="form-label">Telephone:</label>
            <input id="telephone" name="telephone" class="input-block input" value="{{ client.telephone }}"/>
        </div>
        <div class="form-field">
            <label for="contact_name" class="form-label">Contact Name:</label>
            <input id="contact_name" name="contact_name" class="input-block input" value="{{ client.contact_name }}"/>
        </div>
        <div class="form-field">
            <label for="contact_email" class="form-label">Contact Email:</label>
            <input id="contact_email" name="contact_email" class="input-block input"
                   value="{{ client.contact_email }}"/>
        </div>
        <div class="form-field">
            <label for="website" class="form-label">Website:</label>
            <input id="website" name="website" class="input-block input" value="{{ client.website }}"/>
        </div>
        {% include 'core/modal_buttons.html' %}
    </form>
</div>

secretary/templates/secretary/new_project.html
<div id="modal">
    <h2 class="text-xl text-content1">New Project</h2>
    <br>
    <form class="form-group"
          hx-post="{% url 'secretary:new_project' %}" hx-target="#table-body" hx-swap="beforeend"
          _="on htmx:afterRequest set #modal-edit.checked to false wait 200ms then remove #modal">
        {% csrf_token %}
        <div class="form-field">
            <label for="code" class="form-label">Code:</label>
            <input id="code" name="code" class="input-block input"/>
        </div>
        <div class="uk-margin">
            <label for="nom" class="form-label">Name:</label>
            <input id="nom" name="nom" class="input-block input"/>
        </div>
        <div class="uk-margin">
            <label for="description" class="form-label">Description:</label>
            <input id="description" name="description" class="input-block input"/>
        </div>
        <div class="uk-margin">
            <label for="client" class="form-label">Client:</label>
            <select name="client" id="client" class="select select-block">
                {% for organisation in organisations %}
                    <option value="{{ organisation.code }}"{% if organisation.code == project.client.code %}
                            selected{% endif %}>{{ organisation.code }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="uk-margin">
            <label for="start_date" class="form-label">Start Date:</label>
            <input type="date" name="start_date" id="start_date" class="input-block input"/>
        </div>
        <div class="uk-margin">
            <label for="end_date" class="form-label">End Date:</label>
            <input type="date" name="end_date" id="end_date" class="input-block input"/>
        </div>
        {% include 'core/modal_buttons.html' %}
    </form>
</div>

secretary/templates/secretary/project_row.html
<tr id="project-{{ project.code }}">
    <td>{{ project.code }}</td>
    <td>{{ project.nom }}</td>
    <td>{{ project.description | truncatewords:10 }}</td>
    <td>
        <button
                hx-get="{% url 'secretary:edit_project' project.code %}"
                hx-target="#modals-here"
                class="btn btn-ghost"
                _="on htmx:afterOnLoad wait 10ms then set #modal-edit.checked to true">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                 stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M20 14.66V20a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h5.34"></path>
                <polygon points="18 2 22 6 12 16 8 16 8 12 18 2"></polygon>
            </svg>
        </button>
        <button class="link text-red-500"
                hx-target="#project-{{ project.code }}"
                hx-swap="outerHTML swap:1s"
                hx-delete="{% url 'secretary:delete_project' project.code %}"
                hx-confirm="Do you want to delete {{ project.code }} ?">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                 stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <polyline points="3 6 5 6 21 6"></polyline>
                <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
                <line x1="10" y1="11" x2="10" y2="17"></line>
                <line x1="14" y1="11" x2="14" y2="17"></line>
            </svg>
        </button>
    </td>
</tr>

secretary/templates/secretary/projects.html
{% extends 'core/base.html' %}

{% block title %}Projects{% endblock %}

{% block content %}
    <div class="max-w-screen-md mx-auto my-0.5 p-4">
        <table class="table-compact table overflow-x-scroll">
            <thead>
            <tr>
                <th>Code</th>
                <th>Nom</th>
                <th>Description</th>
                <th class="w-20 min-w-[80px]">
                    <button
                            hx-get="{% url 'secretary:new_project' %}"
                            hx-target="#modals-here"
                            class="btn btn-ghost border-transparent"
                            _="on htmx:afterOnLoad wait 10ms then set #modal-edit.checked to true">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                             stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                            <line x1="12" y1="5" x2="12" y2="19"></line>
                            <line x1="5" y1="12" x2="19" y2="12"></line>
                        </svg>
                    </button>
                </th>
            </tr>
            </thead>
            <tbody id="table-body">
            {% for project in projects %}
                {% include 'secretary/project_row.html' %}
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}